### ISSUE TITLE
(question) why use line cookbook for hostfiles instead of hostfiles cookbook?

### ISSUE THREAD

**Issue by vinyar** [chef-cookbooks/chef-reference#1]
reference:
https://github.com/chef-cookbooks/chef-reference/blob/master/recipes/_hostsfile.rb#L26-L36

**Comment by vinyar** [comment]
https://github.com/chef-cookbooks/chef-reference/blob/master/recipes/_hostsfile.rb#L26-L36

**Comment by jtimberman** [comment]
The `line` cookbook is much more simple than `hostsfile`, and thus easier to debug.
