### ISSUE TITLE
launch-zero bug

### ISSUE THREAD

**Issue by bcorner13** [chef-cookbooks/chef-reference#2]
/script/launch-zero 
./script/launch-zero:16:in `<main>': uninitialized constant Chef::LocalMode (NameError)

**Comment by iennae** [comment]
@bcorner13 ,

Thanks for opening this issue. Can you give us more information about your environment, your operating system for example, and any other pertinent information?

Thanks so much!

**Comment by tatemz** [comment]
I get the same error on Mac OSX 10.11.4 (15E65)

I installed the chefdk with homebrew

**Comment by tatemz** [comment]
```
$ chef -v
Chef Development Kit Version: 0.12.0
chef-client version: 12.8.1
berks version: 4.3.0
kitchen version: 1.6.0
```

**Comment by tatemz** [comment]
Adding this to my launch_zero fixed this error:

```
require 'chef'

# Add requirement below requiring chef
require "chef/local_mode"
```
